# Generated by Django 5.0.1 on 2024-02-05 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_the_question', models.CharField(max_length=200, verbose_name='عنوان سوال ')),
                ('question', models.CharField(choices=[('CODE', 'کد '), ('ALGORITHMS', 'الگوریتم'), ('MATH', 'ریاضی'), ('DESIGN', 'طراحی'), ('LEARN', 'یادگیری یا اموزش'), ('OTHER', 'سایر ')], max_length=200, verbose_name='مسئله')),
                ('appendix', models.FileField(blank=True, upload_to='', validators=[django.core.validators.MinValueValidator(limit_value=2097152)], verbose_name='ضمیمه')),
                ('text_question', models.TextField(verbose_name='متن سوال ')),
                ('image', models.ImageField(blank=True, upload_to='', validators=[django.core.validators.MinValueValidator(limit_value=2097152)], verbose_name='انتخاب عکس')),
            ],
            options={
                'verbose_name': 'سوال از مربی های دوره ',
            },
        ),
    ]
