# Generated by Django 5.0.1 on 2024-02-05 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='appendix',
            field=models.FileField(blank=True, help_text='ضمیمه پاسخ ارسالی', upload_to='', validators=[django.core.validators.MinValueValidator(limit_value=2097152)], verbose_name='ضمیمه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, help_text=' انتخاب عکس', upload_to='', validators=[django.core.validators.MinValueValidator(limit_value=2097152)], verbose_name='انتخاب عکس'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='text_question',
            field=models.TextField(help_text='لطفا مشکلی که باهاش مواجه شدین رو اینجا توضیح بدین.', verbose_name='متن سوال '),
        ),
    ]
