# Generated by Django 5.0.1 on 2024-02-06 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_request', '0003_alter_teacher_appendix_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='appendix',
            field=models.FileField(blank=True, help_text='ضمیمه پاسخ ارسالی', upload_to='', validators=[django.core.validators.MinValueValidator(limit_value=2097152), django.core.validators.MaxValueValidator(limit_value=10485760)], verbose_name='ضمیمه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, help_text=' انتخاب عکس', upload_to='', validators=[django.core.validators.MinValueValidator(limit_value=2097152), django.core.validators.MaxValueValidator(limit_value=10485760)], verbose_name='انتخاب عکس'),
        ),
    ]
