# Generated by Django 5.0.1 on 2024-02-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_request', '0004_alter_teacher_appendix_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='appendix',
            field=models.FileField(blank=True, help_text='ضمیمه پاسخ ارسالی', upload_to='', verbose_name='ضمیمه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, help_text=' انتخاب عکس', upload_to='', verbose_name='انتخاب عکس'),
        ),
    ]
