# Generated by Django 5.0.1 on 2024-02-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_request', '0005_alter_teacher_appendix_alter_teacher_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='AskTheTeacher',
        ),
    ]
