# Generated by Django 5.0.1 on 2024-02-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_request', '0006_rename_teacher_asktheteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskTheGBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_the_question', models.CharField(max_length=200, verbose_name='عنوان سوال ')),
                ('question', models.CharField(choices=[('CODE', 'کد '), ('ALGORITHMS', 'الگوریتم'), ('MATH', 'ریاضی'), ('DESIGN', 'طراحی'), ('LEARN', 'یادگیری یا اموزش'), ('OTHER', 'سایر ')], max_length=200, verbose_name='مسئله')),
                ('text_question', models.TextField(help_text='لطفا مشکلی که باهاش مواجه شدین رو اینجا توضیح بدین.', verbose_name='متن سوال ')),
            ],
        ),
        migrations.RenameField(
            model_name='asktheteacher',
            old_name='appendix',
            new_name='file',
        ),
    ]
