# Generated by Django 5.0.1 on 2024-02-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_request', '0007_askthegbt_rename_appendix_asktheteacher_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askthegbt',
            name='question',
            field=models.CharField(max_length=200, verbose_name='مسئله'),
        ),
    ]
