# Generated by Django 5.0.1 on 2024-02-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_request', '0009_alter_askthegbt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='askthegbt',
            options={'verbose_name': 'سوال از ربات QGBT '},
        ),
    ]
