# Generated by Django 5.0.1 on 2024-02-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_request', '0010_alter_askthegbt_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askthegbt',
            name='text_question',
        ),
        migrations.RemoveField(
            model_name='askthegbt',
            name='title_of_the_question',
        ),
        migrations.AddField(
            model_name='askthegbt',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='askthegbt',
            name='question',
            field=models.TextField(),
        ),
    ]
