# Generated by Django 5.0.1 on 2024-02-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_request', '0011_remove_askthegbt_text_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='askthegbt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='asktheteacher',
            options={},
        ),
    ]
